// =====================================================
// ClalMobile — Commission Employees API
// CRUD for standalone employee registry with access tokens
// =====================================================

import { NextRequest } from "next/server";
import { withAdminAuth } from "@/lib/admin/auth";
import { apiSuccess, apiError } from "@/lib/api-response";
import type { SupabaseClient } from "@supabase/supabase-js";

// GET — list all commission employees
export const GET = withAdminAuth(async (_req: NextRequest, db: SupabaseClient) => {
  const { data, error } = await db
    .from("commission_employees")
    .select("*")
    .order("name");

  if (error) {
    console.error("Employees GET error:", error);
    return apiError("فشل في جلب الموظفين", 500);
  }
  return apiSuccess({ employees: data || [] });
});

// POST — create or update employee
export const POST = withAdminAuth(async (req: NextRequest, db: SupabaseClient) => {
  const body = await req.json();
  const { id, name, phone, role, active, notes, user_id } = body;

  if (!name || name.trim().length < 2) return apiError("name required (min 2 chars)", 400);

  if (id) {
    // Update existing
    const updates: Record<string, unknown> = { updated_at: new Date().toISOString() };
    if (name) updates.name = name.trim();
    if (phone !== undefined) updates.phone = phone || null;
    if (role !== undefined) updates.role = role || "sales";
    if (active !== undefined) updates.active = active;
    if (notes !== undefined) updates.notes = notes || null;
    if (user_id !== undefined) updates.user_id = user_id || null;

    const { data, error } = await db
      .from("commission_employees")
      .update(updates)
      .eq("id", id)
      .select()
      .single();

    if (error) {
      console.error("Employees update error:", error);
      return apiError("فشل في تحديث الموظف", 500);
    }
    return apiSuccess(data);
  }

  // Create new — token auto-generated by DB default
  const { data, error } = await db
    .from("commission_employees")
    .insert({
      name: name.trim(),
      phone: phone || null,
      role: role || "sales",
      active: active !== false,
      notes: notes || null,
      user_id: user_id || null,
    })
    .select()
    .single();

  if (error) {
    console.error("Employees create error:", error);
    return apiError("فشل في إضافة الموظف", 500);
  }
  return apiSuccess(data, undefined, 201);
});

// DELETE — remove employee
export const DELETE = withAdminAuth(async (req: NextRequest, db: SupabaseClient) => {
  const { searchParams } = new URL(req.url);
  const id = searchParams.get("id");
  if (!id) return apiError("id required", 400);

  const { error } = await db
    .from("commission_employees")
    .delete()
    .eq("id", id);

  if (error) {
    console.error("Employees DELETE error:", error);
    return apiError("فشل في حذف الموظف", 500);
  }
  return apiSuccess({ deleted: true });
});

// PATCH — regenerate token
export const PATCH = withAdminAuth(async (req: NextRequest, db: SupabaseClient) => {
  const body = await req.json();
  const { id } = body;
  if (!id) return apiError("id required", 400);

  // Generate new UUID token via crypto
  const newToken = crypto.randomUUID();
  const { data, error } = await db
    .from("commission_employees")
    .update({ token: newToken, updated_at: new Date().toISOString() })
    .eq("id", id)
    .select()
    .single();

  if (error) {
    console.error("Employees PATCH error:", error);
    return apiError("فشل في تجديد التوكن", 500);
  }
  return apiSuccess(data);
});
