export const SCHEMA_CONTRACTS = {
  users: {
    rowType: "AppUser",
    factory: "makeUser",
    requiredColumns: [
      "id",
      "auth_id",
      "name",
      "email",
      "role",
      "status",
      "must_change_password",
      "temp_password_expires_at",
      "invited_by",
      "invited_at",
      "last_login_at",
      "created_at",
    ],
    migrationSnippets: [
      "CREATE TABLE users (",
      "ALTER TABLE users ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN NOT NULL DEFAULT false;",
      "ALTER TABLE users ADD COLUMN IF NOT EXISTS temp_password_expires_at TIMESTAMPTZ;",
      "ALTER TABLE users ADD COLUMN IF NOT EXISTS invited_by UUID REFERENCES users(id);",
      "ALTER TABLE users ADD COLUMN IF NOT EXISTS invited_at TIMESTAMPTZ;",
    ],
    documentationSnippets: [
      "`users` | Staff accounts",
      "must_change_password",
      "temp_password_expires_at",
      "invited_by",
      "last_login_at",
    ],
  },
  settings: {
    rowType: "Setting",
    factory: "makeSetting",
    requiredColumns: ["key", "value", "type"],
    migrationSnippets: ["CREATE TABLE settings (", "key TEXT PRIMARY KEY", "value TEXT NOT NULL"],
    documentationSnippets: ["`settings` | Key-value store"],
  },
  integrations: {
    rowType: "Integration",
    factory: "makeIntegration",
    requiredColumns: ["id", "type", "provider", "config", "status", "last_synced_at"],
    migrationSnippets: [
      "CREATE TABLE integrations (",
      "provider TEXT NOT NULL DEFAULT ''",
      "config JSONB NOT NULL DEFAULT '{}'",
      "status TEXT NOT NULL DEFAULT 'inactive'",
    ],
    documentationSnippets: ["`integrations` | Provider config per category"],
  },
  integration_secrets: {
    rowType: "IntegrationSecret",
    factory: "makeIntegrationSecret",
    requiredColumns: [
      "id",
      "integration_id",
      "secret_key",
      "encrypted_value",
      "value_hint",
      "key_version",
      "updated_by",
      "created_at",
      "updated_at",
    ],
    migrationSnippets: [
      "CREATE TABLE IF NOT EXISTS integration_secrets (",
      "secret_key TEXT NOT NULL",
      "encrypted_value TEXT NOT NULL",
      "key_version INT NOT NULL DEFAULT 1",
      "updated_by UUID REFERENCES users(id) ON DELETE SET NULL",
    ],
    documentationSnippets: ["`integration_secrets` | Encrypted vault"],
  },
  products: {
    rowType: "Product",
    factory: "makeProduct",
    requiredColumns: [
      "id",
      "type",
      "brand",
      "name_ar",
      "name_he",
      "price",
      "cost",
      "stock",
      "category_id",
      "active",
      "created_at",
      "updated_at",
    ],
    migrationSnippets: ["CREATE TABLE products (", "type TEXT NOT NULL", "name_ar TEXT NOT NULL", "price NUMERIC(10,2) NOT NULL"],
    documentationSnippets: ["`products` | Catalog"],
  },
  orders: {
    rowType: "Order",
    factory: "makeOrder",
    requiredColumns: [
      "id",
      "customer_id",
      "status",
      "source",
      "total",
      "payment_status",
      "assigned_to",
      "created_at",
      "updated_at",
    ],
    migrationSnippets: ["CREATE TABLE orders (", "status TEXT NOT NULL DEFAULT 'new'", "source TEXT NOT NULL DEFAULT 'store'", "total NUMERIC(10,2) NOT NULL DEFAULT 0"],
    documentationSnippets: ["`orders` | Customer orders"],
  },
  customers: {
    rowType: "Customer",
    factory: "makeCustomer",
    requiredColumns: [
      "id",
      "name",
      "phone",
      "customer_code",
      "segment",
      "total_spent",
      "total_orders",
      "created_at",
      "updated_at",
    ],
    migrationSnippets: ["CREATE TABLE customers (", "phone TEXT NOT NULL UNIQUE", "segment TEXT DEFAULT 'new'"],
    documentationSnippets: ["`customers` | Master customer record"],
  },
  inbox_conversations: {
    rowType: "InboxConversation",
    factory: "makeInboxConversation",
    requiredColumns: [
      "id",
      "customer_phone",
      "customer_name",
      "channel",
      "status",
      "assigned_to",
      "assigned_at",
      "priority",
      "pinned",
      "is_blocked",
      "unread_count",
      "last_message_text",
      "last_message_at",
      "last_message_direction",
      "first_response_at",
      "resolved_at",
      "resolved_by",
      "source",
      "metadata",
      "sentiment",
      "created_at",
      "updated_at",
    ],
    migrationSnippets: [
      "CREATE TABLE IF NOT EXISTS inbox_conversations (",
      "channel TEXT NOT NULL DEFAULT 'whatsapp'",
      "unread_count INTEGER DEFAULT 0",
      "metadata JSONB DEFAULT '{}'",
      "ALTER TABLE inbox_conversations ADD COLUMN IF NOT EXISTS sentiment TEXT DEFAULT 'neutral';",
    ],
    documentationSnippets: [
      "`inbox_conversations` | Unified conversation header",
      "sentiment",
    ],
  },
  inbox_messages: {
    rowType: "InboxMessage",
    factory: "makeInboxMessage",
    requiredColumns: [
      "id",
      "conversation_id",
      "direction",
      "sender_type",
      "sender_id",
      "sender_name",
      "message_type",
      "content",
      "media_url",
      "media_mime_type",
      "media_filename",
      "template_name",
      "template_params",
      "reply_to_id",
      "whatsapp_message_id",
      "status",
      "error_message",
      "metadata",
      "created_at",
    ],
    migrationSnippets: [
      "CREATE TABLE IF NOT EXISTS inbox_messages (",
      "conversation_id UUID NOT NULL REFERENCES inbox_conversations(id) ON DELETE CASCADE",
      "message_type TEXT NOT NULL DEFAULT 'text'",
      "metadata JSONB DEFAULT '{}'",
    ],
    documentationSnippets: [
      "`inbox_messages` | Every message, inbound or outbound",
      "delivery status",
    ],
  },
  inbox_labels: {
    rowType: "InboxLabel",
    factory: "makeInboxLabel",
    requiredColumns: ["id", "name", "color", "description", "sort_order", "created_at"],
    migrationSnippets: [
      "CREATE TABLE IF NOT EXISTS inbox_labels (",
      "name TEXT NOT NULL",
      "color TEXT NOT NULL DEFAULT '#666666'",
    ],
    documentationSnippets: [
      "`inbox_labels` | Colored tags",
      "VIP, Urgent, Complaint",
    ],
  },
  inbox_conversation_labels: {
    rowType: "InboxConversationLabel",
    factory: "makeInboxConversationLabel",
    requiredColumns: ["conversation_id", "label_id"],
    migrationSnippets: [
      "CREATE TABLE IF NOT EXISTS inbox_conversation_labels (",
      "PRIMARY KEY (conversation_id, label_id)",
    ],
    documentationSnippets: [
      "`inbox_conversation_labels` | Join table",
      "(conversation_id, label_id)",
    ],
  },
  inbox_notes: {
    rowType: "InboxNote",
    factory: "makeInboxNote",
    requiredColumns: ["id", "conversation_id", "author_id", "author_name", "content", "created_at"],
    migrationSnippets: [
      "CREATE TABLE IF NOT EXISTS inbox_notes (",
      "conversation_id UUID NOT NULL REFERENCES inbox_conversations(id) ON DELETE CASCADE",
      "content TEXT NOT NULL",
    ],
    documentationSnippets: [
      "`inbox_notes` | Internal-only notes inside a conversation",
      "not sent to the customer",
    ],
  },
  inbox_templates: {
    rowType: "InboxTemplate",
    factory: "makeInboxTemplate",
    requiredColumns: [
      "id",
      "name",
      "category",
      "content",
      "variables",
      "is_active",
      "usage_count",
      "sort_order",
      "created_by",
      "created_at",
      "updated_at",
    ],
    migrationSnippets: [
      "CREATE TABLE IF NOT EXISTS inbox_templates (",
      "variables TEXT[] DEFAULT '{}'",
      "is_active BOOLEAN DEFAULT true",
      "usage_count INTEGER DEFAULT 0",
    ],
    documentationSnippets: [
      "`inbox_templates` | Bilingual message templates",
      "usage counter",
    ],
  },
  inbox_quick_replies: {
    rowType: "InboxQuickReply",
    factory: "makeInboxQuickReply",
    requiredColumns: [
      "id",
      "shortcut",
      "title",
      "content",
      "category",
      "usage_count",
      "sort_order",
      "is_active",
      "created_at",
    ],
    migrationSnippets: [
      "CREATE TABLE IF NOT EXISTS inbox_quick_replies (",
      "shortcut TEXT NOT NULL UNIQUE",
      "is_active BOOLEAN DEFAULT true",
    ],
    documentationSnippets: [
      "`inbox_quick_replies` | Slash-commands",
      "`/hi`, `/price`",
    ],
  },
  inbox_events: {
    rowType: "InboxEvent",
    factory: "makeInboxEvent",
    requiredColumns: [
      "id",
      "conversation_id",
      "event_type",
      "actor_id",
      "actor_name",
      "old_value",
      "new_value",
      "created_at",
    ],
    migrationSnippets: [
      "CREATE TABLE IF NOT EXISTS inbox_events (",
      "conversation_id UUID REFERENCES inbox_conversations(id) ON DELETE CASCADE",
      "event_type TEXT NOT NULL",
    ],
    documentationSnippets: [
      "`inbox_events` | Timeline events",
      "assignment changes, status changes, label add/remove",
    ],
  },
  commission_sales: {
    rowType: "CommissionSale",
    factory: "makeCommissionSale",
    requiredColumns: [
      "id",
      "sale_date",
      "sale_type",
      "source",
      "order_id",
      "customer_id",
      "commission_amount",
      "contract_commission",
      "rate_snapshot",
      "source_sales_doc_id",
      "source_pipeline_deal_id",
      "employee_id",
      "deleted_at",
      "created_at",
      "updated_at",
    ],
    migrationSnippets: [
      "ALTER TABLE commission_sales ADD CONSTRAINT commission_sales_source_check",
      "CHECK (source IN ('manual', 'auto_sync', 'csv_import', 'sales_doc', 'pipeline', 'order'));",
      "ADD COLUMN IF NOT EXISTS rate_snapshot JSONB;",
      "ADD COLUMN IF NOT EXISTS source_sales_doc_id BIGINT",
      "ADD COLUMN IF NOT EXISTS source_pipeline_deal_id UUID",
    ],
    documentationSnippets: ["`commission_sales` | One row per commissionable sale", "rate_snapshot", "source_sales_doc_id", "source_pipeline_deal_id"],
  },
  sales_docs: {
    rowType: "SalesDoc",
    factory: "makeSalesDoc",
    requiredColumns: [
      "id",
      "doc_uuid",
      "employee_user_id",
      "employee_key",
      "customer_id",
      "order_id",
      "sale_type",
      "status",
      "total_amount",
      "currency",
      "source",
      "idempotency_key",
      "cancelled_at",
      "cancelled_by",
      "cancellation_reason",
      "created_at",
      "updated_at",
      "deleted_at",
    ],
    migrationSnippets: [
      "CREATE TABLE IF NOT EXISTS sales_docs (",
      "status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'submitted', 'verified', 'rejected', 'synced_to_commissions'))",
      "ALTER TABLE sales_docs ADD CONSTRAINT sales_docs_status_check",
      "CHECK (status IN ('draft', 'submitted', 'verified', 'rejected', 'synced_to_commissions', 'cancelled'));",
      "ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ",
      "ADD COLUMN IF NOT EXISTS cancelled_by TEXT",
      "ADD COLUMN IF NOT EXISTS cancellation_reason TEXT",
    ],
    documentationSnippets: ["`sales_docs` | Sales-documentation headers", "cancelled", "cancellation_reason"],
  },
} as const;

export type SchemaContractTable = keyof typeof SCHEMA_CONTRACTS;
