/**
 * POST /api/pwa/sales/[id]/attachments
 *
 * Records attachment metadata AFTER the client has uploaded the file to the
 * signed URL obtained from /sign. Verifies the file exists in the expected
 * path — prevents audit issue 4.3 (fake metadata with no real file).
 */

import { NextRequest } from "next/server";
import { apiError, apiSuccess, safeError } from "@/lib/api-response";
import { createAdminSupabase } from "@/lib/supabase";
import { requireEmployee } from "@/lib/pwa/auth";
import { validateBody } from "@/lib/admin/validators";
import { attachmentMetadataSchema, MAX_ATTACHMENT_SIZE_BYTES } from "@/lib/pwa/validators";

const BUCKET = "sales-docs-private";
const EXPECTED_PATH_PREFIX = "sales-docs/";

export async function POST(req: NextRequest, ctx: { params: Promise<{ id: string }> }) {
  try {
    const authed = await requireEmployee(req);
    if ("status" in authed) return authed;

    const db = createAdminSupabase();
    if (!db) return apiError("DB unavailable", 500);

    const { id } = await ctx.params;
    const docId = Number(id);
    if (!docId || Number.isNaN(docId)) return apiError("Invalid id", 400);

    const { data: doc } = await db
      .from("sales_docs")
      .select("id, employee_key, status")
      .eq("id", docId)
      .is("deleted_at", null)
      .single();

    if (!doc) return apiError("Not found", 404);
    if (doc.employee_key !== authed.appUserId) return apiError("Forbidden", 403);
    if (!["draft", "rejected"].includes(doc.status)) {
      return apiError("لا يمكن إضافة مرفقات لهذه الحالة", 400);
    }

    const body = await req.json();
    const validation = validateBody(body, attachmentMetadataSchema);
    if (validation.error || !validation.data) {
      return apiError(validation.error || "Invalid payload", 400);
    }

    const payload = validation.data;

    // Path must have been generated by /sign — guard against injection
    if (!payload.file_path.startsWith(`${EXPECTED_PATH_PREFIX}${docId}/`)) {
      return apiError("مسار الملف غير صالح", 400);
    }

    // Verify the file actually exists in Storage (fixes audit 4.3)
    const { data: listed, error: listErr } = await db.storage
      .from(BUCKET)
      .list(payload.file_path.split("/").slice(0, -1).join("/"), {
        limit: 100,
        search: payload.file_path.split("/").pop(),
      });

    if (listErr) {
      console.error("[attachments] storage list failed:", listErr);
      return apiError("فشل في التحقق من الملف", 500);
    }

    const fileName = payload.file_path.split("/").pop();
    const fileEntry = (listed || []).find((f) => f.name === fileName);
    if (!fileEntry) {
      return apiError("الملف غير موجود في التخزين — ارفعه أولاً", 400);
    }

    // Sanity check the reported size vs actual metadata (if available)
    const actualSize = (fileEntry.metadata as { size?: number } | undefined)?.size;
    if (actualSize !== undefined) {
      if (actualSize !== payload.file_size) {
        return apiError("حجم الملف لا يطابق المسجّل", 400);
      }
      if (actualSize > MAX_ATTACHMENT_SIZE_BYTES) {
        return apiError("حجم الملف يتجاوز الحد الأقصى", 400);
      }
    }

    const now = new Date().toISOString();

    const { data: inserted, error } = await db
      .from("sales_doc_attachments")
      .insert({
        sales_doc_id: docId,
        attachment_type: payload.attachment_type,
        file_path: payload.file_path,
        file_name: payload.file_name,
        mime_type: payload.mime_type,
        file_size: payload.file_size,
        sha256: payload.sha256 || null,
        uploaded_by: authed.appUserId,
        created_at: now,
      })
      .select("*")
      .single();

    if (error || !inserted) return apiError("فشل في حفظ المرفق", 500);

    await db.from("sales_doc_events").insert({
      sales_doc_id: docId,
      event_type: "attachment_added",
      actor_user_id: authed.appUserId,
      actor_role: authed.role,
      payload: {
        attachment_type: inserted.attachment_type,
        file_name: inserted.file_name,
        mime_type: inserted.mime_type,
      },
    });

    return apiSuccess(inserted, undefined, 201);
  } catch (err: unknown) {
    return safeError(err, "PWA Attachments POST", "خطأ في السيرفر", 500);
  }
}
